fix build (#2)
fix the following issue
```
$ sudo snap install aws-cli
error: This revision of snap "aws-cli" was published using classic confinement
       and thus may perform arbitrary system changes outside of the security
       sandbox that snaps are usually confined to, which may put your system at
       risk.
       If you understand and want to proceed repeat the command including
       --classic.
```